version: '2'
catalog:
  name: "Alpine Linux v3.6 4 Java Tech Group Day #5"
  version: 3.6
  description: "Run Alpine Linux during Java Tech Group Day #5"
  questions:
    - variable: options_enum
      label: "Select an option"
      description: "Set the value of the options_enum environment variable"
      default: Java
      required: true
      type: enum
      options: 
        - Java
        - Tech
        - Group
        - Day
        - \#5
    - variable: options_boolean
      label: "Enter a boolean value"
      description: "Set the value of the options_boolean environment variable"
      default: true
      required: true
      type: "boolean"
    - variable: options_string
      label: "Enter a string"
      description: "Set the value of the options_string environment variable"
      default: "Java Tech Group Day #5"
      required: true
      type: "string"
alpine-3.6:
  scale: 1